### ISSUE TITLE
volver a iniciar

### ISSUE THREAD

**Issue by degoxec98** [EliNayli/TRIVIA-B-BLICA-2#1]
### Describe the bug

1. El programa no cuenta con un ciclo para volver a correr a intentar otra vez.

### To produce
1. El usuario no podrá volver a intentarlo.
2. El juego podría volverse un poco monótono porque es lineal y de una sola iteración

### Posible solución

```
bandera = True
while (bandera):
   intento +=1

   [Todo tu código]

   x = input("Deseas volver a intentarlo?")
   if x!='si':
      bandera = False
      print("Mensaje de despedida")
```

**Comment by EliNayli** [comment]
Thanks you voy a corregirlo.

**Comment by EliNayli** [comment]
DESCRIBE THE BUG:

1. El usuario no podrá volver a intentarlo.
2. El juego podría volverse un poco monótono porque es lineal y de una sola iteración

TO PRODUCE:

1. He usado una función que agrupa mi juego para que se vuelva a iterar.
2. El jugador estará cómodo jugando nuevamente

SOLUCIÒN:
iniciar_juego = True 
while iniciar_juego == True: 

-----preguntas----
print("\nRealizaste",intentos,"intento(s)"," ¿Deseas jugar nuevamente?")
  repetir_juego = input(MAGENTA+"Ingresa 'si' para repetir, o cualquier tecla para finalizar: "+RESET).lower()
  if repetir_juego != "si":
    print(MAGENTA+"Espero que lo hayas pasado bien, vuelve pronto"+RESET)
    iniciar_juego = False 

**le dejo el link de mi nuevo replit:**
https://replit.com/@ELIZABETHCURO/TRIVIA-BiBLICA-2#main.py
