### ISSUE TITLE
No mostrar la tecla del mensaje secreto

### ISSUE THREAD

**Issue by degoxec98** [EliNayli/TRIVIA-B-BLICA-2#2]
### Descripción

En la parte donde se pide ingresar nuevamente la respuesta (en caso haya ingresado una tecla inválida) que se muestra a continuación:

https://github.com/EliNayli/TRIVIA-B-BLICA-2/blob/ce3536b4789b13ee0a90464520c8eeae5326b9d2/main.py#L18

Se muestra la tecla de la respuesta secreta (o mensaje secreto) la cuál es `*`

### Importancia

Por cuestiones de tener una mejor jugabilidad sería bueno que el mensaje no muestre la tecla, pues, la idea de la respuesta secreta es que el usuario descubra por si mismo la tecla de la respuesta secreta.

**Comment by EliNayli** [comment]
Creo que si vendría bien una ayudita :) al jugador, en cuanto a la respuesta solo se muestra cuando ingresa otra opción aparte del a,b o c.
