### ISSUE TITLE
Agregar colores a la trivia

### ISSUE THREAD

**Issue by degoxec98** [EliNayli/TRIVIA-B-BLICA-2#3]
### Descripción

El programa no cuenta con colores para que el usuario pueda diferenciar en caso haya respondido correctamente o se haya equivocado, o para algúna otra parte como las instrucciones.

### Importancia

Los colores son importantes para que el usuario no se confunda si respondió bien o mal. Además, nos ayuda a enfatizar ciertas partes importantes de nuestro programa como el caso de las instrucciones o el puntaje que se va acumulando.

### Posible solución

Como posible solución se podría declarar las siguientes constantes en la parte inicial de nuestro código:
```
RED = '\033[31m'    #Color rojo
GREEN = '\033[32m'  #Color verde
RESET = '\033[39m'  #Finaliza el color
```

Y luego se podría utilizar para dar color rojo `RED` en caso se haya contestado mal o verde `GREEN`  si contestó bien, como en el siguiente ejemplo:
```
print(GREEN, "Respuesta correcta!", RESET) #En caso sea correcto
print(RED, "Respuesta incorrecta!", RESET) #En caso sea incorrecto
```

**Comment by EliNayli** [comment]
Gracias ya lo ingresé.

**Comment by EliNayli** [comment]
Descripción
El programa no cuenta con colores para que el usuario pueda diferenciar en caso haya respondido correctamente o se haya equivocado, o para algúna otra parte como las instrucciones.

Importancia
Bueno es cierto que los colores llaman la atención y permiten diferenciar el contenido, por ello he considerado agregarlo.

Posible solución
En mi caso use estos colores:

RED = '\033[31m'    #Color Rojo  para mencionar errores
BLUE = '\033[34m'  #Color Azul para las opciones de respuestas
MAGENTA = '\033[35m' #Color Fucsia para textos de bienvenida, preguntas y finalización
GREEN = '\033[32m'  #Color Verde para felicitar, notas y puntajes
WHITE = '\033[37m' #Color blanco para el nombre del jugador e ingresar variables
RESET = '\033[39m'  #Finaliza el color
